CREATE DATABASE hcid_tool_db;

USE hcid_tool_db;

CREATE TABLE address_list (
	id INTEGER AUTO_INCREMENT NOT NULL,
    street_num INTEGER(40) NOT NULL,
	street_name VARCHAR(40) NOT NULL,
    street_type VARCHAR(40) NOT NULL,
    street_dir_cd VARCHAR(40) NOT NULL,
    street_unit VARCHAR(40),
    city VARCHAR(40),
    state VARCHAR(40) NOT NULL,
    zipcode INTEGER(40),
	is_active BOOLEAN NOT NULL DEFAULT TRUE,
	createdAt TIMESTAMP DEFAULT NOT NULL CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
);

CREATE TABLE bims (
	id INTEGER AUTO_INCREMENT NOT NULL,
    StatementNum INTEGER(40) NOT NULL,
	StatementDate VARCHAR(40) NOT NULL,
    APN INTEGER(10) NOT NULL,
    Property_Address VARCHAR(40) NOT NULL,
    Property_City_State_Zip VARCHAR(40),
    RSO_Exemptions INTEGER(10),
    SCEP_Exmpetions INTEGER(10) NOT NULL,
    IS_RSO VARCHAR(40),
    IS_SCEP VARCHAR(40),
    RSO_Invoice_Num INTEGER(10),
    SCEP_Invoice_Num INTEGER(10),
    Total_Units INTEGER(10),
    RSO_Units_Billed INTEGER(10),
    SCEP_Units_Billed INTEGER(10),
	is_active BOOLEAN NOT NULL DEFAULT TRUE,
	createdAt TIMESTAMP DEFAULT NOT NULL CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
);

CREATE TABLE hims (
	id INTEGER AUTO_INCREMENT NOT NULL,
    HOUSEING_PROGRAM VARCHAR(20),
	ProjUniqueID VARCHAR(20),
    ProjectNo VARCHAR(20),
    PROJECT_STATUS VARCHAR(20),
    PROJECT_INFO VARCHAR(20),
    APN INTEGER(10),
    HouseId INTEGER(10),
    HouseNum INTEGER(10),
    HouseFracNum INTEGER(40),
    PIN INTEGER(10),
    CouncilDistric VARCHAR(20),
    PreDirCd VARCHAR(20),
    StreetName VARCHAR(20),
    StreetTypeCd VARCHAR(20),
    PostDirCd VARCHAR(20),
    UnitRange VARCHAR(20),
    Unit_Number VARCHAR(20),
    ZipCode VARCHAR(20),
    City VARCHAR(20),
    LAHD_Count VARCHAR(20),
    LUPAM_Count VARCHAR(20),
    IsInFloodZone VARCHAR(20),
    CensusTract VARCHAR(20),
	is_active BOOLEAN NOT NULL DEFAULT TRUE,
	createdAt TIMESTAMP DEFAULT NOT NULL CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
);

CREATE TABLE prop_site_address (
	id INTEGER AUTO_INCREMENT NOT NULL,
    Apn INTEGER(40),
    HouseID INTEGER(40),
    Pin INTEGER(40),
    HouseNum INTEGER(40),
    HouseFracNum INTEGER(40),
    PreDirCd VARCHAR(40),
    StreetName VARCHAR(40),
    StreetTypeCd VARCHAR(40),
    PostDirCd VARCHAR(40),
    UnitRange VARCHAR(40),
    City VARCHAR(40),
    Zip INTEGER(40),
    ZipSuffix INTEGER(40),
    XCoord INTEGER(40),
    YCoord INTEGER(40),
    Lon INTEGER(40),
    Lat INTEGER(40),
    Pind INTEGER(40),
    EngDist VARCHAR(40),
    CouncilDistrict VARCHAR(40),
    LupLandUseCd VARCHAR(40),
    FlgHistMonument VARCHAR(40),
    LutCodeOfficeCd VARCHAR(40),
    LutRentAreaCd VARCHAR(40),
    LutHistPresZoneCd VARCHAR(40),
    TbmPage VARCHAR(40),
    TbmRow VARCHAR(40),
    TbmCol VARCHAR(40),
    CenTract2010 VARCHAR(40),
    CenBlock2010GeoID VARCHAR(40),
    CenBlock2010 VARCHAR(40),
    CenBlockGrp2010 VARCHAR(40),
    CommunityName VARCHAR(40),
    FlgInsideCoi VARCHAR(40),
    CraRedevCd VARCHAR(40),
    StateAssemDist VARCHAR(40),
    StateSenDist VARCHAR(40),
    UsCongDist VARCHAR(40),
    CountySupDistNum VARCHAR(40),
    CommunityPlanAreaID VARCHAR(40),
    NeighborhoodCouncilID VARCHAR(40),
    FlgNsp1 VARCHAR(40),
    FlgNsp2 VARCHAR(40),
    FlgNsp3 VARCHAR(40),
    HseAssignedCd VARCHAR(40),
    HseFlgDeleted VARCHAR(40),
    ApnFlgDeleted VARCHAR(40),
	is_active BOOLEAN NOT NULL DEFAULT TRUE,
	createdAt TIMESTAMP DEFAULT NOT NULL CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
);

CREATE TABLE prop_unit (
	id INTEGER AUTO_INCREMENT NOT NULL,
    APN INTEGER(40),
    UnitID INTEGER(40),
    BldgID INTEGER(40),
    HouseID INTEGER(40),
    BldgUnitID INTEGER(40),
    propbldgid INTEGER(40),
    LutUnitStatusCd VARCHAR(40),
    UnitNum VARCHAR(40),
    LegacyUnitNum VARCHAR(40),
    DateBuilt VARCHAR(40),
    DateDemolished VARCHAR(40),
    LutModReasonCd VARCHAR(40),
    LutModVerifiedCd VARCHAR(40),
    ModComment VARCHAR(40),
	is_active BOOLEAN NOT NULL DEFAULT TRUE,
	createdAt TIMESTAMP DEFAULT NOT NULL CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
);

CREATE TABLE rent (
	id INTEGER AUTO_INCREMENT NOT NULL,
    APN INTEGER(40),
    Property_Address VARCHAR(40),
    Service_Date VARCHAR(40),
    Land_Use_Code VARCHAR(40),
    Unit_Count INTEGER(40),
    Exempted_Units INTEGER(40),
    RSO_Units INTEGER(40),
    Year_Built VARCHAR(40),
    Category VARCHAR(40),
    Council_District INTEGER(40),
    Secondary_Address VARCHAR(40),
    houseID INTEGER(40),
    FC_NOTES VARCHAR(40),
	is_active BOOLEAN NOT NULL DEFAULT TRUE,
	createdAt TIMESTAMP DEFAULT NOT NULL CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
);

CREATE TABLE scep (
	id INTEGER AUTO_INCREMENT NOT NULL,
    propID INTEGER(40),
    PermExemptions INTEGER(40),
    TotalExemptions INTEGER(40),
    councilDistrictNo INTEGER(40),
    censusTract INTEGER(40),
    yearBuilt INTEGER(40),
    units INTEGER(40),
    APN INTEGER(40),
    landUseDesc VARCHAR(40),
    CodeDistrict VARCHAR(40),
    CodeDistrictID INTEGER(40),
    HouseNum VARCHAR(40),
    StreetName VARCHAR(40),
    Property_Address VARCHAR(40),
    StreetDirection VARCHAR(40),
    FlgDeleted VARCHAR(40),
	is_active BOOLEAN NOT NULL DEFAULT TRUE,
	createdAt TIMESTAMP DEFAULT NOT NULL CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
);